name: Build I-Creator APK

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:

      # =====================================================
      # 1. CHECKOUT
      # =====================================================
      - name: Checkout Code
        uses: actions/checkout@v4


      # =====================================================
      # 2. SETUP FLUTTER
      # =====================================================
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.0'
          channel: stable
          cache: true


      # =====================================================
      # 3. CREATE FLUTTER PROJECT
      # =====================================================
      - name: Create Flutter Project
        run: |
          flutter create \
            --org com.bharatstream.app \
            --project-name i_creator \
            --platforms android \
            build_project

      - name: Print SHA-1 Fingerprint
        working-directory: build_project/android
        run: |
          mkdir -p ~/.config/.android
              yes android | keytool -genkey -v -keystore ~/.config/.android/debug.keystore
              chmod +x gradlew
                  ./gradlew signingReport
      # =====================================================
      # 4. COPY APP FILES
      # =====================================================
      - name: Copy App Files
        run: |
          cp pubspec.yaml build_project/pubspec.yaml
          cp -r lib/* build_project/lib/ 
          rm -rf build_project/test

      # =====================================================
      # 5. SETUP JAVA
      # =====================================================
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: '17'


      # =====================================================
      # 6. FLUTTER PUB GET
      # =====================================================
      - name: Flutter Pub Get
        working-directory: build_project
        run: |
          flutter pub get


      # =====================================================
      # 7. FLUTTER ANALYZE
      # =====================================================
      - name: Flutter Analyze
        working-directory: build_project
        run: |
          flutter analyze


      # =====================================================
      # 8. BUILD APK
      # =====================================================
      - name: Build Release APK
        working-directory: build_project
        run: |
          flutter build apk --release --no-tree-shake-icons


      # =====================================================
      # 9. UPLOAD APK
      # =====================================================
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: I-Creator-APK
          path: build_project/build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
